version: '3'

services:
  backend:
    build: ./
    container_name: nestjs_api
    environment:
      - PORT = 3000
      - MONGO_URI = mongodb+srv://ec2-user:password_mongodb@aws-mongodb-cluster.sbcegsr.mongodb.net/
      - JWT_SECRET_KEY = 46fb0d0c4f4044d2381a7e3f8a1535d1697b7a44c066a7eb5c47a6492b6e2682
    ports:
      - '3000:3000'
    depends_on:
      - database
    networks: 
      - nestjs_network
  
  database:
    image: mongo
    ports:
      -'27017:27017'
    networks:
      - nestjs_network
networks:
  nestjs_network:
    driver: bridge
