version: '3'

services:
  backend:
    build: ./
    container_name: nestjs_api
    environment:
      - PORT = 3000
      - DB_TYPE=postgres
      - DB_PORT=5432
      - DB_HOST=localhost
      - DB_USERNAME=postgres
      - DB_PASSWORD=Rishikkesh@12
      - DB_NAME=nft_marketplace
      - JWT_SECRET_KEY=46fb0d0c4f4044d2381a7e3f8a1535d1697b7a44c066a7eb5c47a6492b6e2682
    ports:
      - '3000:3000'
    depends_on:
      - database
    networks:
      - nestjs_network
  
  database:
    image: postgres
    ports:
      -'5432:5432'
networks:
  nestjs_network:
    driver: bridge
